Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 17, in <module>
    import setuptools.version
  File "/usr/lib/python3/dist-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
    tuple(
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3280, in <genexpr>
    dist.activate(replace=False)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2784, in activate
    fixup_namespace_packages(self.location)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2296, in fixup_namespace_packages
    subpath = _handle_ns(package, path_item)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2200, in _handle_ns
    with warnings.catch_warnings():
  File "/usr/lib/python3.8/warnings.py", line 465, in __enter__
    self._showwarning = self._module.showwarning
KeyboardInterrupt
